apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/zapkub/argocd-test-app
    targetRevision: main
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
